language: java
sudo: false # faster builds

jdk:
    - oraclejdk10
    - oraclejdk9
    - oraclejdk8

install:
    - ./mvnw clean install -DskipTests=true -Dcheckstyle.skip=true -Drat.skip=true -Dmaven.javadoc.skip=true

script:
    - travis_wait 30 ./mvnw test

after_success:
    - bash <(curl -s https://codecov.io/bash)
