sudo: false # faster builds
os: linux
dist: focal
arch: arm64-graviton2
virt: lxd
group: edge

language: java
jdk: openjdk11

cache:
  directories:
    - $HOME/.m2

install: true

branches:
  only:
    - '3.0'

before_script:
  - rm -rf $HOME/.m2/repository/org/glassfish/javax.el/3.0.1-b08

script: if [[ "${TRAVIS_EVENT_TYPE}" == "cron" ]]; then travis_wait 60 ./mvnw --batch-mode -U -q -e --no-transfer-progress clean test -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Dmaven.wagon.http.retryHandler.count=5 -DskipTests=false -DskipIntegrationTests=false -Dcheckstyle.skip=false -Drat.skip=false -Dmaven.javadoc.skip=true;  fi

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - echo "build failed!"
