language: java
sudo: false # faster builds

jdk:
    - oraclejdk9
    - oraclejdk8
    - openjdk7

cache:
  directories:
  - '$HOME/.m2/repository'

install:
  - ./mvnw clean install -DskipTests=true -Dcheckstyle.skip=false -Dmaven.javadoc.skip=false -Drat.skip=false

script:
    - travis_wait 30 ./mvnw test

after_success:
  - bash <(curl -s https://codecov.io/bash)
